config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'challenges#new'

  match '/404', to: 'errors#global_error', via: :all
  match '/422', to: 'errors#global_error', via: :all
  match '/500', to: 'errors#global_error', via: :all
  resources :challenges, only: %i[new index create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
# == Schema Information
#
# Table name: challenges
#
#  id              :integer          not null, primary key
#  number          :integer
#  opponent_number :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :integer          not null
#
# Indexes
#
#  index_challenges_on_user_id  (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Challenge < ApplicationRecord
  belongs_to :user

  validates :number, presence: true

  def tie?
    number.eql? opponent_number
  end

  def winner?
    opponent_number.even? ? number > opponent_number : number < opponent_number
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  encrypted_password     :string           default(""), not null
#  last_name              :string           default(""), not null
#  name                   :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  username               :string           default(""), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable
  validates :username, :last_name, :name, :password, presence: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(_)
    new_challenge_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name last_name username])
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :authenticate_user!

  def index
    @challenges = Challenge.all.order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @last_challenge = Challenge.last
  end

  def create
    result = CreateChallenge.call(params: challenge_params,
                                  user: current_user)
    redirect_to new_challenge_path and return if result.success?

    raise ActionController::RoutingError.new('Not Found')
  end

  private

  def challenge_params
    params.require(:challenge).permit(:number)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def global_error; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/views/challenges/index.html.erb
<%= render "shared/navbar" %>
<div class="list">
  <div class="text-center mb-2">
    <h1>Listado de juegos</h1>
  </div>
  <div class="table">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Tu número</th>
          <th scope="col">Número del contrincante</th>
          <th scope="col">Resultado</th>
        </tr>
      </thead>
      <tbody>
        <% @challenges.each do |challenge| %>
          <% presenter = ChallengePresenter.new(challenge) %>
          <tr>
            <td><%= challenge.number %></td>
            <td><%= challenge.opponent_number %></td>
            <td><%= presenter.winner_text %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @challenges %>  
  </div>
</div>

app/views/challenges/new.html.erb
<%= render "shared/navbar" %>
<% presenter = ChallengePresenter.new(@last_challenge) %>
<div class="dashboard">
  <div class="text-center mb-2">
    <h1>Bienvenido</h1>
    <span class="username"><%= current_user.username %> </span>
  </div>
  <div class="rules">
    <span class="title">Reglas</span>
    <ul>
      <li>
        <span>
          Si el número elegido para el contrincante corresponde a un número par, gana el jugador que tenga un número más alto.
        </span>
      </li>
      <li>
        <span>
          Si el número elegido para el contrincante es un número impar, gana el jugador que tenga un número más bajo.
        </span>
      </li>
      <li>
        <span>
          El número ingresado debe estar entre 1 y 10
        </span>
      </li>
    </ul>
  </div>
  <%- if @last_challenge -%>
    <div class="last-game text-center">
      <span class="title">Resultado del último juego</span>
      <div class="item">
        <span>
          Tu número: <%= @last_challenge.number %>
        </span>
      </div>
      <div class="item">
        <span>
          El número de tu oponente: <%= @last_challenge.opponent_number %>
        </span>
      </div>
      <div class="item">
        <span class="result">
          <%= presenter.winner_text %>
        </span>
      </div>
    </div>
  <% end %>

  <div class="game mt-2 mb-2">
    <div class="text-center">
      <span>
       ¡Preparate para jugar!
      </span>
    </div>
    <div class="text-center">
      <span>
       Que la suerte este contigo
      </span>
    </div>
  </div>

  <div class="new-game">
    <%= form_for :challenge, url: '/challenges', data: { controller: 'validate', target: 'validate.form' } do |f| %>
      <%= f.number_field :number, class: 'form-control', data: { target: 'validate.input',
                                                                    validate: { presence: { message: '^Ingresa un número'},
                                                                                numericality: { message: '^Número invalido',
                                                                                                greaterThan: 0,
                                                                                                onlyInteger: true,
                                                                                                lessThanOrEqualTo: 10 } } } %>
      <%= f.submit 'Juego', class: 'button mt-2', data: { action: 'validate#submitForm'} %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Iniciar Sesión", new_session_path(resource_name), class: "links" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Crear Cuenta", new_registration_path(resource_name), class: "links" %><br />
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <span class="navbar-brand">Amazing Game</span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Lista", challenges_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to "Juego", new_challenge_path, class: 'nav-link active' %>
        </li>
      </ul>
      <div class="logout">
        <span>
          <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: 'links' %>
        </span>
      </div>
    </div>
  </div>
</nav>